Add section 2.2
jneidel/internet.org-entwicklung pull request #10
Opened 2019-11-30 22:37 UTC by jneidel

Als pdf:
[main.pdf](https://github.com/jneidel/internet.org-entwicklung/files/3907623/main.pdf)

2019-12-01 18:49 UTC, Daelerion requested changes

2019-12-01 18:49 UTC, Daelerion commented on main.tex
>  In der Zwischenzeit versuchte Facebook, nach initellen Startschwierigkeiten, die Initiative durch Rebranding zu retten, was aber nicht reichte um die kritische Öffentlichkeit zu beeinflußen, deren Me
```suggestion
In der Zwischenzeit versuchte Facebook, nach initiellen Startschwierigkeiten, die Initiative durch Rebranding zu retten, was aber nicht reichte um die kritische Öffentlichkeit zu beeinflussen, deren Meinung bis zu den Entscheidungsträgern der zuständigen Behörde vordringen konnte.
```

2019-12-01 18:49 UTC, Daelerion commented on main.tex
> +Auch ist die Qualität (Geschwindigkeit) des Services, welche 4-12 mal langsamer ist, lässt sich nicht mit dem eines zahlenden Kunden vergleichen.
```suggestion
Auch lässt sich die Qualität (Geschwindigkeit) des Services, welche 4-12 mal langsamer ist, nicht mit der eines zahlenden Kunden vergleichen.
```

2019-12-01 18:49 UTC, Daelerion commented on main.tex
> +Die langsame Verbindung hat dabei mehrere Gründe. Zum einen wird die Bandbreite von Reliance gedrosselt um den zahlenden Abonnenten Vorrang zu geben. Auch laufen alle Verbindungen durch einen Faceboo
Hört sich etwas kantig an, evtl Sätze zusammenführenm wie z.B:

```suggestion
Die langsame Verbindung hat dabei mehrere Gründe. Zum einen wird die Bandbreite von Reliance gedrosselt um den zahlenden Abonnenten Vorrang zu geben. Auch laufen alle Verbindungen durch einen Facebook Proxy Server in Europa, was dazu führt, dass die Route erheblich verlängert,  erneut gedrosselt, und jegliche Verschlüsslung (TLS) umgangen wird(Vgl. \cite{walledGarden}).
```

Obwohl das evtl schon zu klumpig aussieht ^^

2019-12-01 18:49 UTC, Daelerion commented on main.tex
> +Airtel Ankündigung wurde mit einer Welle der Entrüstung aufgenommen, worauf hin Airtel auch schnell von der Idee abließ.
```suggestion
Airtel's Ankündigung wurde mit einer Welle der Entrüstung aufgenommen, worauf hin Airtel auch schnell von der Idee abließ.
```
+

Evtl. kurz klarifizieren, wer / was "Airtel" überhaupt ist

2019-12-01 19:07 UTC, jneidel commented on main.tex
> +Airtel Ankündigung wurde mit einer Welle der Entrüstung aufgenommen, worauf hin Airtel auch schnell von der Idee abließ.
Aus Abschnitt 1.2.3 geht hervor das Airtel ein Mobilfunk provider ist.

2019-12-02 14:27 UTC, Daelerion approved these changes

2019-12-02 18:03 UTC, merged